create database db_upa;
use db_upa;

CREATE TABLE MEDICO(
 CRM INT PRIMARY KEY,
 NOME VARCHAR(50) NOT NULL,
 EMAIL VARCHAR(20) NOT NULL,
 TELEFONE INT UNIQUE,
 DATA_NASC DATE,
 ESPECIALIZACAO VARCHAR(25), 
 CHECK (ESPECIALIZACAO IN ('CARDIOLOGISTA', 'NUTRICIONISTA'))
);
CREATE TABLE PACIENTE(
    ID int primary key,
    CPF int unique,
    Nome varchar(100),
    Endereco varchar (75),
    Telefone int unique,
    Tipo_Exame varchar(25) 
    check (Tipo_Exame in ('laboratorial', 'clinico'))
);
CREATE TABLE CONSULTA (
    ID_MEDICO INT NOT NULL,
    ID_PACIENTE INT NOT NULL,
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(CRM),
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID), 
    DATA_CONSULT DATE NOT NULL,
    VALOR DOUBLE NOT NULL,
    TIPO_PAG VARCHAR(20) UNIQUE
);
CREATE TABLE EXAME (
    ID_MEDICO INT NOT NULL,
    ID_PACIENTE INT NOT NULL,
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(CRM),
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID), 
    DATA_EXAME DATE,
    HORARIO TIME,
    VALOR DOUBLE NOT NULL,
    TIPO_PAG VARCHAR(20) UNIQUE,
    TIPO_EXAME VARCHAR(50) UNIQUE
);
insert INTO MEDICO (CRM,NOME,EMAIL,TELEFONE,DATA_NASC,ESPECIALIZACAO)
VALUES
('5487','CAIO NOBREGA','CAIOA@GMAIL.COM','981254879','1997-09-27','NUTRICIONISTA'),
('8749','ERIC SALES','ERIC@GMAIL.COM','993573105','1988-01-19','CARDIOLOGISTA'),
('6589','BENICIO','BENICIO@GMAIL.COM','98180306','1997-05-22','CARDIOLOGISTA');

SELECT * FROM MEDICO;
INSERT INTO PACIENTE (ID,CPF,NOME,ENDERECO,TELEFONE)
VALUES
(1,'7065487','CAIO','PB','874556','CLINICO'),
(2,'8457968','MATEUS','JP','859764','laboratorial'),
(3,'7856325','NIEDSON','AL','569852','CLINICO'),
(4,'6542589','WALBERG','SP','569854','laboratorial'),
(5,'5487589','JOAO','AM','458786','CLINICO');

SELECT*FROM PACIENTE;

INSERT INTO CONSULTA (ID_MEDICO,ID_PACIENTE,DATA_CONSULT,VALOR,TIPO_PAG)
VALUES
(5487,3,'2025-05-05',250.00,'CARTAO'),
(8749,1,'2024-10-24',350.00,'ESPECIE'),
(5487,1,'2023-08-20',400.00,'DEBITO'),
(8749,1,'2021-10-25',500.00,'TED');

select*from consulta;

DELETE FROM PACIENTE WHERE ID = 2;


UPDATE PACIENTE
SET telefone =14517
where id = 4;


select * from paciente 

select nome,especializacao from medico;

select consulta from 


select nome,data_nasc
from medico 
where data_nasc > 1997-05-22;



select * from medico where especializacao ='cardiologista';

SELECT COUNT(*) AS total_paciente
FROM paciente;

SELECT AVG(VALOR)
AS Valor_medio
FROM consulta;

select min(data_consult)
from consulta;
