CREATE DATABASE SGE;
/*USANDO O BANCO*/
/*USANDO*/
USE SGE;
/*CRIANDO  A PRIMEIRA TABELA*/
CREATE TABLE ALUNOS (
ID_ALUNO INT auto_increment PRIMARY KEY,
NOME VARCHAR (100),
DATA_NASC DATE
);
/*ADICIONANDO COLUNA NA TABELA ALUNO*/
ALTER TABLE ALUNOS
ADD COLUMN EMAIL VARCHAR (50);

/*CRIANDO SEGUNDA TABELA*/
CREATE TABLE CURSOS (
ID_CURSOS INT auto_increment PRIMARY KEY,
NOME_CURSO VARCHAR (50),
CARGA_HORARIA INT,
DISCIPLINAS VARCHAR (75),
HORARIOS datetime
);
/* ADICIONANDO COLUNA NA TABELA CURSOS*/
ALTER TABLE CURSOS
ADD COLUMN PRECO DECIMAL (10,2);

/*ADICIONANDO UMA COLUNA ID_CURSOS NA TABELA ALUNOS*/
ALTER TABLE  ALUNOS 
ADD COLUMN ID_CURSOS INT;

ALTER TABLE CURSOS
MODIFY HORARIOS TIME;

/*ADICONANDO CHAVE ESTRANGUEIRA ID_CURSOS NA TABELA CURSOS PARA FAZER LIGAÇÃO ENRE TABELAS*/
ALTER TABLE ALUNOS
ADD CONSTRAINT FK_ALUNOS_CURSOS
FOREIGN KEY (ID_CURSOS) REFERENCES CURSOS(ID_CURSOS);

/*ADICIONANDO CRUSOS*/
INSERT INTO CURSOS (NOME_CURSO, CARGA_HORARIA, PRECO, DISCIPLINAS,HORARIOS)
VALUES
('MEDICINA', 400, 1200, 'REPRODUTORA', '08:00:00'),
('ENGENHARIA', 350, 2500, 'PLANAGEM', '13:00:00'),
('ARQUITETURA', 1500, 1200, 'PAISAGEM MODERNA', '13:00:00');

select *from cursos;

INSERT INTO ALUNOS(nome,data_nasc,email)
values 
('caio','1999-10-25','caio@gmail.com'),
('benicio','1988-01-19','benicio@gmail.com'),
('valberto','1998-12-25','valberto@gmail.com'),
('carme','2000-08-10','carme@gmail.com');

SELECT * FROM ALUNOS;
/* TABELA MATRICULAS PARA FAZER LIGACAO  ALUNO COM CURSO*/
CREATE TABLE MATRICULAS (
  ID_MATRICULA INT AUTO_INCREMENT PRIMARY KEY,
  ID_ALUNO INT NOT NULL,
  ID_CURSOS INT NOT NULL,
  DATA_MATRICULA DATE NOT NULL,
  CONSTRAINT FK_MATRICULAS_ALUNO
    FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(ID_ALUNO),
  CONSTRAINT FK_MATRICULAS_CURSO
    FOREIGN KEY (ID_CURSOS) REFERENCES CURSOS(ID_CURSOS)
);

INSERT INTO MATRICULAS (ID_ALUNO, ID_CURSOS, DATA_MATRICULA)
VALUES
(1, 1, '2025-03-01'),
(1, 2, '2025-03-05'),
(2, 2, '2025-03-02'),
(3, 3, '2025-03-10'),
(4, 1, '2025-03-12');

SELECT * FROM MATRICULAS;

CREATE TABLE PROFESSORES (
  ID_PROFESSOR INT AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100),
  ESPECIALIDADE VARCHAR(80)
);


INSERT INTO PROFESSORES (NOME, EMAIL, ESPECIALIDADE)
VALUES
('Dr. João Silva', 'joao@gmail.com','medicina'),
('Maria Costa', 'maria@gmail.com', 'engenharia'),
('Carlos Mendes', 'carlos@gmail.com', 'arquitetura');


/* CRIANDO TABELA  Q FAZ LIGACAO DO PROFESSOR COM CURSO*/
CREATE TABLE CURSOS_PROFESSORES (
  ID_CURSO_PROF INT AUTO_INCREMENT PRIMARY KEY,
  ID_CURSOS INT NOT NULL,
  ID_PROFESSOR INT NOT NULL,

  CONSTRAINT FK_CP_CURSO
    FOREIGN KEY (ID_CURSOS) REFERENCES CURSOS(ID_CURSOS),

  CONSTRAINT FK_CP_PROFESSOR
    FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSORES(ID_PROFESSOR)
);

INSERT INTO CURSOS_PROFESSORES (ID_CURSOS, ID_PROFESSOR)
VALUES
(1, 1), 
(2, 2),
(3, 3); 

SELECT * FROM CURSOS_PROFESSORES;

/* SELECIONANDO PROFESSOR COM O CURSO E SUA ESPECIALIDADE*/
SELECT 
  c.NOME_CURSO,
  p.NOME AS PROFESSOR,
  p.ESPECIALIDADE
FROM CURSOS c
JOIN CURSOS_PROFESSORES cp ON c.ID_CURSOS = cp.ID_CURSOS
JOIN PROFESSORES p ON p.ID_PROFESSOR = cp.ID_PROFESSOR;
